[package]
name = "cosmos_hypervisor"
version = "0.1.0"
edition = "2021"

[dependencies]
cosmos_message_api = { path = "../cosmos_message_api" }
cosmos_core = { path = "../cosmos_core" }
arrayvec = "0.7.6"
