[package]
name = "state_objects"
version = "0.1.0"
edition = "2021"

[dependencies]
cosmos_state_api = { path = "../cosmos_state_api" }
cosmos_context = { path = "../cosmos_context" }
cosmos_schema = { path = "../cosmos_schema" }
arrayvec = "0.7.6"